const BookingAction = {
    GET_ROOM_TO_CART: 'GET_ROOM_TO_CART',
    BOOKING_START: 'BOOKING_START',
    PAYMENT : 'PAYMENT',
    RESERVATION_DETAIL: 'RESERVATION_DETAIL',
    RESERVATION_CANCEL : 'RESERVATION_CANCEL',
}
export default BookingAction