const SettingAction = {
    CHANGEPASS:'CHANGEPASS',
    CHANGEPASS_SUCCESS: 'CHANGEPASS_SUCCESS',
    CHANGEPASS_ERROR: 'CHANGEPASS_ERROR',
    GET_PROFILE: 'GET_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    GET_HISTORY_RESERVATIONS: 'GET_HISTORY_RESERVATIONS',
}
export default SettingAction