const HostAction = {
    GET_HOTEL: 'GET_HOTEL',
    ADD_HOTEL: 'ADD_HOTEL',
    ADD_ROOM_TYPE: 'ADD_ROOM_TYPE',
    GET_ROOMTYPES: 'GET_ROOMTYPES',
    GET_ROOM_AVAILABLE: 'GET_ROOM_AVAILABLE',
    UPDATE_ROOMTYPE: 'UPDATE_ROOMTYPE',
    GET_RESERVED_ROOM_INFO: 'GET_RESERVED_ROOM_INFO',
    UPDATE_HOTEL: 'UPDATE_HOTEL',
    REVENUE_HOTEL_BY_YEAR: 'REVENUE_HOTEL_BY_YEAR',
    DELETE_ROOMTYPE: 'DELETE_ROOMTYPE',
    GET_SERVICES: 'GET_SERVICES',
    GET_AMENITIES: 'GET_AMENITIES',
    GET_VIEWS: 'GET_VIEWS',
    GET_LIST_HOTELS: 'GET_LIST_HOTELS',
    SEARCH_ROOMTYPE: 'SEARCH_ROOMTYPE',
}
export default HostAction